name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Run every day at midnight UTC
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write          # ✅ This line is REQUIRED to allow pushing to output branch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo content
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Generate snake animation
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ABUBAKAR-DAHIR
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push generated files to the output branch
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
